---
github:
  - metadata
remote_theme: dieghernan/chulapa
locale: es-ES
title: Arcanum Caedis
title_separator: null
subtitle: null
description: null
url: null
baseurl: null
repository: JMEsquerdo/arcanumcaedis
words_per_minute: null
timezone: Europe/Madrid
og_image: null
twitter_site: null
author:
  name: Arcanum Caedis
  avatar: null
  location: Madrid, Spain
fa_version: null
fa_kit_code: null
fa_v4_support: null
gtag_id: null
analytics_id: null
search:
  provider: fusejs
  label: null
  landing_page: null
  lunr_maxwords: null
  maxwords: null
  show_attrib: null
  algolia_logo: true
google_cse_id: null
algolia:
  application_id: null
  index_name: null
  search_only_api_key: null
  files_to_exclude:
    - _layouts/*.html
    - _includes/*.html
  extensions_to_index:
    - html
    - md
  searchableAttributes:
    - title
    - headings
    - unordered(content)
    - unordered(subtitle)
    - unordered(categories)
    - unordered(collection)
    - unordered(tags)
  customRanking:
    - desc(include_on_search)
    - desc(title)
    - desc(content)
    - desc(subtitle)
comments:
  provider: null
  disqus_shortname: null
  cactus_shortname: null
navbar:
  style: fab
  expand: null
  brand:
    title: Home
    url: null
    img: null
  nav:
    - title: Blog
      url: /blog/
    - title: Cheatsheets
      url: /cheatsheets
    - title: Extras
      child:
        - title: Tags
          url: /tags
        - title: Categories
          url: /categories
        - title: Archive
          url: /archive
        - title: Current skin
          url: /current-skin
footer:
  links:
    - label: Repo on Github
      icon: fab fa-github
      url: https://github.com/JMEsquerdo/arcanumcaedis
    - label: RSS
      icon: fa fa-rss
      url: ./atom.xml
  copyright: null
googlefonts:
  googlefonts: https://fonts.googleapis.com/css2?family=Quintessential&family=Cormorant+Garamond&family=Quattrocento+Sans:wght@400;700&display=swap
chulapa-skin:
  highlight: null
  skin: null
  autothemer: true
  vars:
    primary: "#1f4068"
    secondary: "#d4af37"
    success: "#28a745"
    danger: "#8b0000"
    info: "#3ca3e6"
    warning: "#e0a800"
    light: "#fdf6e3"
    dark: "#0b1a2b"
    headings-font-family: "'Quintessential', cursive"
    subtitle-font-family: "'Cormorant Garamond', serif"
    font-family-sans-serif: "'Quattrocento Sans', sans-serif"
paginate: 4
paginate_path: /blog/page:num/
paginator_maxnum: 3
collections:
  cheatsheet:
    output: true
    permalink: /cheatsheets/:name
collections_dir: null
permalink: /:year:month:day_:title/
defaults:
  - scope:
      path: ""
    values:
      layout: default
      header_type: base
      include_on_search: false
      cloudtag_url: /tags
      cloudcategory_url: /categories
  - scope:
      path: ""
      type: posts
    values:
      header_type: post
      include_on_search: true
      include_on_feed: true
      show_date: true
      show_related: true
      show_bottomnavs: true
      show_sociallinks: true
      show_comments: true
      show_tags: true
      show_categories: true
      show_author: true
      show_breadcrumb: true
      breadcrumb_list:
        - label: Blog
          url: /blog/
  - scope:
      path: ""
      type: cheatsheet
    values:
      header_type: hero
      show_bottomnavs: true
      show_sociallinks: true
      include_on_search: true
      show_breadcrumb: true
      breadcrumb_list:
        - label: Cheatsheets
          url: /cheatsheets
compress_html:
  clippings: all
  blanklines: true
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
include:
  - _pages
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: "&uarr;"
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - mixed-decls
    - function-units
    - color-functions
    - abs-percent